name: Check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: erlef/setup-elixir@v1
      with:
        elixir-version: 1.11.3
        otp-version: 23.2
    - name: Cache Elixir Dependencies
      uses: actions/cache@v2
      with:
        path: |
         _build/dev/lib
         _build/test/lib
        key: ${{ runner.os }}-elixir-cache-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.OS }}-elixir-cache-
    - name: Install Elixir Dependencies
      run: mix deps.get
    - name: Compile
      run: mix compile
    - name: Credo
      run: mix credo
